// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SkillSwap.Infrastructure.Data;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(SkillSwapDbContext))]
    partial class SkillSwapDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.6");

            modelBuilder.Entity("SkillSwap.Core.Usuarios.Models.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("SkillSwap.Core.Usuarios.Models.Usuario", b =>
                {
                    b.OwnsOne("SkillSwap.Core.Usuarios.Models.InformacoesUsuario", "Perfil", b1 =>
                        {
                            b1.Property<Guid>("UsuarioId")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("Id")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Nome")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("UsuarioId");

                            b1.ToTable("InformacoesUsuarios");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioId");

                            b1.OwnsOne("SkillSwap.Core.Usuarios.ValueObjects.DadosEmpresa", "Empresa", b2 =>
                                {
                                    b2.Property<Guid>("InformacoesUsuarioUsuarioId")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("DominioAcesso")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("RazaoSocial")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.HasKey("InformacoesUsuarioUsuarioId");

                                    b2.ToTable("InformacoesUsuarios");

                                    b2.WithOwner()
                                        .HasForeignKey("InformacoesUsuarioUsuarioId");

                                    b2.OwnsOne("SkillSwap.Core.Usuarios.ValueObjects.Cnpj", "CNPJ", b3 =>
                                        {
                                            b3.Property<Guid>("DadosEmpresaInformacoesUsuarioUsuarioId")
                                                .HasColumnType("TEXT");

                                            b3.Property<string>("Valor")
                                                .IsRequired()
                                                .HasColumnType("TEXT");

                                            b3.HasKey("DadosEmpresaInformacoesUsuarioUsuarioId");

                                            b3.ToTable("InformacoesUsuarios");

                                            b3.WithOwner()
                                                .HasForeignKey("DadosEmpresaInformacoesUsuarioUsuarioId");
                                        });

                                    b2.Navigation("CNPJ")
                                        .IsRequired();
                                });

                            b1.OwnsOne("SkillSwap.Core.Usuarios.ValueObjects.Endereco", "Endereco", b2 =>
                                {
                                    b2.Property<Guid>("InformacoesUsuarioUsuarioId")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Bairro")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Cep")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Cidade")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Complemento")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Estado")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Numero")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Rua")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.HasKey("InformacoesUsuarioUsuarioId");

                                    b2.ToTable("InformacoesUsuarios");

                                    b2.WithOwner()
                                        .HasForeignKey("InformacoesUsuarioUsuarioId");
                                });

                            b1.OwnsOne("SkillSwap.Core.Usuarios.ValueObjects.Telefone", "Telefone", b2 =>
                                {
                                    b2.Property<Guid>("InformacoesUsuarioUsuarioId")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Numero")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.HasKey("InformacoesUsuarioUsuarioId");

                                    b2.ToTable("InformacoesUsuarios");

                                    b2.WithOwner()
                                        .HasForeignKey("InformacoesUsuarioUsuarioId");
                                });

                            b1.Navigation("Empresa");

                            b1.Navigation("Endereco");

                            b1.Navigation("Telefone")
                                .IsRequired();
                        });

                    b.Navigation("Perfil");
                });
#pragma warning restore 612, 618
        }
    }
}
